# Use a lightweight Java image
FROM openjdk:17-jdk-slim

# Set working directory
WORKDIR /app

# Copy the compiled JAR file
COPY target/MySQL_MicroService-0.0.1-SNAPSHOT.jar /app/app.jar

# Expose the gRPC server port
EXPOSE 9090

# Command to run the gRPC application
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
