version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_user
      MONGO_INITDB_ROOT_PASSWORD: secure_password
    networks:
      - app_network

  mongodb_microservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mongodb_microservice
    ports:
      - "8082:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin_user:secure_password@mongodb:27017/mongodb_microservice
    depends_on:
      - mongodb
    networks:
      - app_network

networks:
  app_network:
